- name: functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps,Linux,Shell,Ansiblr # string
    gmail: "HAREESH.reddy@gmail.com"
    ipaddress: "187.126.08.35"
    # dictionary == map
    tags:
      Application: payment
      Environment: dev
    # List
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Ramesh') }}"
  
  # string to list
  - name: convert string to list 
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json }}"

  - name: save json to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"

  - name: convert lowercase
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

  - name: check IP is valid or not
    ansible.builtin.debug: "{{ ipaddress | ansible.utils.ipv4 }}"

    # here ansible is python builtin right so we have to install python in server before execution command
    # for checking which ansible version  ( ansible --version)
    # command is (  pip3.9 netaddr)
    # ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 18-ipaddress.yaml